<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="LoadingBay.Product.props" />
  <PropertyGroup>
    <RustyEngineProductEntryType>LoadingBay.Game.LoadingBayProduct</RustyEngineProductEntryType>
    <RustyEngineProductId>loading-bay.e1m1</RustyEngineProductId>
    <RustyEngineProductTitle>Loading Bay — Doom E1M1</RustyEngineProductTitle>
  </PropertyGroup>
</Project>
