"""Compile retained Doom atlas metadata to typed recipe presentation data, offline."""
import json
import sys
import struct
import zlib
from pathlib import Path
root = Path(__file__).resolve().parents[2]
manifest = json.loads((root / 'content/doom-e1m1/sprites/manifest.json').read_text())
lines = ['// Generated by scripts/authoring/generate-recipe-sprites.py; retained sprite manifest owns provenance.', 'using System.Numerics;', 'namespace LoadingBay.Game;', 'internal readonly record struct RecipeSpriteFrame(string Atlas, Vector2 Min, Vector2 Max, Vector2 Size, Vector2 Pivot);', 'internal static class LoadingBayRecipeSprites', '{', '    internal static RecipeSpriteFrame Frame(string name) => name switch', '    {']
for atlas in manifest['atlases']:
    for f in atlas['frames']:
        def vec(v): return 'new(' + ', '.join(format(n, '.9g')+'f' for n in v) + ')'
        lines.append(f'        "{f["name"]}" => new("{atlas["file"]}", {vec(f["uv"]["min"])}, {vec(f["uv"]["max"])}, {vec([n/32 for n in f["pixelSize"]])}, {vec(f["pivot"])}),')
# Atlas uses generated RGBA8/filter-none source rows; preserve all source pixels.
source = (root / 'content/doom-e1m1/sprites/weapons.png').read_bytes()
at, packed = 8, bytearray()
while at < len(source):
    count = struct.unpack_from('>I', source, at)[0]
    kind = source[at+4:at+8]; data = source[at+8:at+8+count]
    if kind == b'IHDR': sw, sh, depth, color, _, _, interlace = struct.unpack('>IIBBBBB', data)
    if kind == b'IDAT': packed.extend(data)
    at += count + 12
assert (depth, color, interlace) == (8, 6, 0)
raw = zlib.decompress(packed)
assert all(raw[y*(sw*4+1)] == 0 for y in range(sh)), 'Expected retained filter-none atlas'
frames = [f for a in manifest['atlases'] for f in a['frames'] if f['family'] in ('PUNG','PISG','PISF','SHTG','SHTF')]
canvas_width, canvas_height, gutter = 320, 168, 2
width, cell_height = canvas_width + 2*gutter, canvas_height + 2*gutter
height = cell_height * len(frames)
rgba = bytearray(width * height * 4)
for index, f in enumerate(frames):
    ax, ay, fw, fh = f['atlasRect']
    ox, oy = f['origin']
    for y in range(fh):
        dy = y - oy
        if not 0 <= dy < canvas_height: continue
        for x in range(fw):
            dx = x - ox
            if not 0 <= dx < canvas_width: continue
            src = (ay+y)*(sw*4+1)+1+(ax+x)*4
            dst = ((index*cell_height+gutter+dy)*width+gutter+dx)*4
            rgba[dst:dst+4] = raw[src:src+4]
    lines.append(f'        "view/{f["name"]}" => new("recipe-viewmodels.png", new({(gutter+.5)/width:.9g}f, {(index*cell_height+gutter+.5)/height:.9g}f), new({(gutter+canvas_width-.5)/width:.9g}f, {(index*cell_height+gutter+canvas_height-.5)/height:.9g}f), new(10f, 6.3f), new(.5f, .5f)),')
# Every cell has a transparent moat; UV endpoints lie at interior texel centers.
# Adjacent opaque bottom rows cannot wrap into the next frame's transparent top.
for index in range(len(frames)):
    for y in [index*cell_height, index*cell_height+cell_height-1]:
        assert not any(rgba[y*width*4:(y+1)*width*4]), 'Nontransparent atlas gutter'
def chunk(kind, data):
    return struct.pack('>I', len(data))+kind+data+struct.pack('>I', zlib.crc32(kind+data))
pixels = b''.join(b'\0'+rgba[y*width*4:(y+1)*width*4] for y in range(height))
png = b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR', struct.pack('>IIBBBBB',width,height,8,6,0,0,0))+chunk(b'IDAT', zlib.compress(pixels,9))+chunk(b'IEND',b'')
asset = root / 'content/loading-bay/recipe-viewmodels.png'
if '--check' in sys.argv:
    if asset.read_bytes() != png: raise SystemExit('Recipe viewmodel atlas is stale; regenerate it.')
else:
    asset.write_bytes(png)
lines += ['        _ => throw new System.ArgumentException("Unknown retained Doom sprite", nameof(name)),', '    };', '}']
target = root / 'csharp/LoadingBay.Game/LoadingBayRecipeSprites.g.cs'
content = '\n'.join(lines)+'\n'
if '--check' in sys.argv:
    if target.read_text() != content: raise SystemExit('Recipe sprite catalog is stale; regenerate it.')
    print('Recipe sprite catalog matches retained manifest.')
else:
    target.write_text(content)
